Fix race condition in test
zopefoundation/zope.sendmail pull request #38
Opened 2020-12-18 19:22 UTC by mgedmin

We had a unit test spawning two threads attempting to run self.test_send_multiple_same_mailer() twice, concurrently.  This works badly when both instances try to mutate self.smtp_hook and verify values on self.smtp.

Closes #15.

2020-12-18 23:21 UTC, mauritsvanrees requested changes
All tox tests pass locally. When running the peppy and pypy3 tests twenty times, they all pass. So that is good.

But the method `test_send_multiple_same_mailer` has this comment about what it is testing:

> The mailer re-opens itself as needed when sending multiple mails.

I don't think this is actually tested anymore.
I think `self._makeMailer` should be called before starting the loop `for run in (1, 2)`.
When I try that, the tests still pass, also when tried twenty times.

2020-12-18 23:21 UTC, mauritsvanrees commented on src/zope/sendmail/tests/test_mailer.py
> +            mailer = self._makeMailer(smtp_hook=smtps.append)
So this line should be moved a few lines up.

2020-12-18 23:22 UTC, mauritsvanrees commented on src/zope/sendmail/tests/test_mailer.py
>          for run in (1, 2):
The line `mailer = self._makeMailer(smtp_hook=smtps.append)` should be called before starting the `for` loop.

2020-12-19 13:04 UTC, jamadden approved these changes

2020-12-19 13:13 UTC, mgedmin commented
Ideally I'd like to have working CI (#37) before we merge this.

2020-12-21 10:45 UTC, mauritsvanrees approved these changes

2020-12-22 15:48 UTC, mgedmin commented
Rebased on master to get working CI (GitHub Actions).

2020-12-22 16:24 UTC, merged